FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    tcpdump \
    curl \
    wget \
    iproute2 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install flask flask-cors requests

CMD ["bash"]
