FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    iptables \
    tcpdump \
    nmap \
    arping \
    libpcap-dev \
    iproute2 \
    procps \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["bash"]
