version: "3"

networks:
  arp_test_net:
    driver: bridge
    driver_opts:
      parent: wlan0
    ipam:
      config:
        - subnet: 172.29.50.0/24 # Using a subnet in your range but likely not in use
          gateway: 172.29.50.1 # Arbitrary gateway within the subnet

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: gateway
    networks:
      arp_test_net:
        ipv4_address: 172.29.50.10
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true
    tty: true

  victim:
    build:
      context: .
      dockerfile: Dockerfile.victim
    container_name: victim
    networks:
      arp_test_net:
        ipv4_address: 172.29.50.20
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ../src:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  attacker:
    build:
      context: .
      dockerfile: Dockerfile.attacker
    container_name: attacker
    networks:
      arp_test_net:
        ipv4_address: 172.29.50.30
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ../src:/app
    stdin_open: true
    tty: true
